export default {
    Free: {
        host: 'imap.free.fr',
        port: 993,
        tls: true,
        tag: ['@free.fr', '@alice.'],
    },
    Yahoo: {
        host: 'imap.mail.yahoo.com',
        port: 993,
        tls: true,
        tag: ['@yahoo.com', '@ymail.com'],
    },
    AOL: {
        host: 'imap.aol.com',
        port: 993,
        tls: true,
        tag: ['@aol.com', '@verizon.net'],
    },
    Rediffmail: {
        host: 'imap.rediffmailpro.com',
        port: 993,
        tls: true,
        tag: ['@rediffmail.com'],
    },
    'AT&T': {
        host: 'imap.mail.att.net',
        port: 993,
        tls: true,
        tag: [
            '@att.net',
            '@ameritech.net',
            '@bellsouth.net',
            '@flash.net',
            '@nvbell.net',
            '@pacbell.net',
            'prodigy.net',
            '@sbcglobal.net',
            '@snet.net',
            '@swbell.net',
            '@wans.net',
        ],
    },
    Outlook: {
        host: 'imap-mail.outlook.com',
        port: 993,
        tls: true,
        tag: ['@live.com', '@outlook.com', '@hotmail.com', '@msn.com', '@passport.com', '@passport.net'],
    },
    Freenet: {
        host: 'mx.freenet.de',
        port: 993,
        tls: true,
        tag: ['@freenet.de'],
    },
    'Mail.com': {
        host: 'imap.mail.com',
        port: 993,
        tls: true,
        tag: [
            '@mail.com',
            '@email.com',
            '@usa.com',
            '@myself.com',
            '@consultant.com',
            '@post.com',
            '@europe.com',
            '@asia.com',
            '@iname.com',
            '@writeme.com',
            '@dr.com',
            '@cheerful.com',
            '@accountant.com',
            '@techie.com',
            '@engineer.com',
            '@linuxmail.org',
            '@musician.org',
            '@contractor.net',
            '@financier.com',
            '@workmail.com',
        ],
    },
    Orange: {
        host: 'imap.orange.fr',
        port: 993,
        tls: true,
        tag: ['@orange.fr', '@wanadoo.fr'],
    },
    'Mail-ru': {
        host: 'imap.mail.ru',
        port: 993,
        tls: true,
        tag: ['mail.ru'],
    },
    Arcor: {
        host: 'imap.arcor.de',
        port: 143,
        tls: false,
        tag: ['@arcor.de'],
    },
    NTL: {
        host: 'imap.ntlworld.com',
        port: 993,
        tls: true,
        tag: ['@ntlworld.com'],
    },
}
